zestedesavoir/zmarkdown

- packages/html-blocks/index.js
- test/fixtures/misc/html.html
- test/fixtures/misc/html.txt
* e.g. `||<p>||` works as expected, it does `<kbd>&gt;p></kbd>` instead of `<kbd></kbd><p>&gt;p></p>`
> Fix html-blocks to be wrapped in some inlines

- README.md
- test/fixtures/zds/extensions/urlize.html
- test/fixtures/zds/extensions/urlize.txt
- test/test.js
Le plugin urlize a bien changé entre pyzmarkdown et zmarkdown. 
J'ai documenté les choses telles qu'elles sont aujourd'hui afin de lancer la discussion.
amha : 
- l'absence de mailto est une régression
- ne pas urlizer google.com (ou www.google.com) est un comportement souhaitable
- la gestion des caractères spéciaux dans les urls est mal faite
> Documente les changements de urlize

- packages/remark-custom-blocks/__tests__/fixtures/regression-1.expected.html
- packages/remark-custom-blocks/__tests__/fixtures/regression-1.fixture.md
- packages/remark-custom-blocks/__tests__/index.js
On https://zestedesavoir.com,
```
content before
[[s]]
|Not Block
with content after
```
gives:
```
<p>content before</p>
<div class="spoiler"><p>Not Block</p></div>
<p>with content after</p>
```
So,the test *regression-1* should be changed to fix #49
> Change regression-1 because the test was incorrect.

- packages/rebber/__tests__/fixtures/blockquote.expected.tex
- packages/rebber/__tests__/fixtures/blockquote.fixture.md
- packages/rebber/__tests__/index.js
- packages/rebber/src/one.js
- packages/rebber/src/types/blockquote.js
This PR adds blockquote support for mdast->latex compilation.
This uses the `Quotation` environment as defined in [this line](https://github.com/zestedesavoir/latex-template/blob/76021abc62562a02628a40a3a52f07fbd80a07a1/zmdocument.cls#L160).
I did not use a "standard" quotation environment as latex has many standard to do that.
Be careful, this will trully work only if #61 is handled. For now I use "anonymous" placeholder for empty source.
> rebber blockquote

- packages/remark-fix-guillemets/LICENSE-MIT
- packages/remark-fix-guillemets/README.md
- packages/remark-fix-guillemets/__tests__/__snapshots__/index.js.snap
- packages/remark-fix-guillemets/__tests__/index.js
- packages/remark-fix-guillemets/dist/index.js
- packages/remark-fix-guillemets/package.json
- packages/remark-fix-guillemets/remark-textr.js
- packages/remark-fix-guillemets/src/index.js
cf #80 
Now:
```
<<html>> <<html1>> <<html2>> <<html3>> <<html4>> <<**bold**>>
```
gives:
```
<p>«html» «html1» «html2» «html3» «html4» «<strong>bold</strong>»</p>
```
> Fix <<html>> issue.

- packages/remark-ping/__tests__/__snapshots__/index.js.snap
- packages/remark-ping/__tests__/index.js
- packages/remark-ping/src/index.js
- packages/zmarkdown/package.json
- packages/zmarkdown/remark-config.js
Requested in https://github.com/zestedesavoir/zds-site/pull/4617 (fr).
Any `@mention` will be considered valid and will be transformed to an
HTML link. That link will point to a non-existent web page (showing a
404 error) if the mentioned username doesn't exist, but it's not a big
deal.
> zmarkdown: don't ensure pinged usernames exist

- packages/zmarkdown/__tests__/__snapshots__/latex.tests.js.snap
- packages/zmarkdown/__tests__/__snapshots__/old-suite-latex.test.js.snap
- packages/zmarkdown/config/rebber.js
inlineCode cause trouble with special char (due to mintinline).
inlineCode use now texttt instead of mintinline and special char
need to be escaped.
Related in [this template PR](https://github.com/zestedesavoir/latex-template/pull/80)
> fix/inline-code: Fix issue with inlineCode

- packages/rebber-plugins/__tests__/__snapshots__/rebber.test.js.snap
- packages/rebber-plugins/__tests__/fixtures/blocks.fixture.md
- packages/rebber-plugins/__tests__/rebber.test.js
- packages/rebber-plugins/dist/type/customBlocks.js
- packages/rebber-plugins/src/type/customBlocks.js
- packages/remark-custom-blocks/README.md
- packages/remark-custom-blocks/__tests__/__snapshots__/index.js.snap
- packages/remark-custom-blocks/__tests__/index.js
- packages/remark-custom-blocks/dist/index.js
- packages/remark-custom-blocks/src/index.js
- packages/zmarkdown/__tests__/__snapshots__/latex.tests.js.snap
- packages/zmarkdown/__tests__/__snapshots__/old-suite-latex.test.js.snap
- packages/zmarkdown/__tests__/fixtures/zds/extensions/customblock.html
- packages/zmarkdown/config/remark.js
- packages/zmarkdown/index.js
This integrates two functionality in the way zmd uses custom-block:
- neutral block (new type of block)
- titled block (extends the syntax)
I make the syntax extension compatible with the old syntax so that without changing anything we can upgrade the remark-custom-block dependency.
For now, I just push the titles into a bare `paragraph` node. I don't know if this is what we expect or if it needs to be enhanced.
The former issue #184 just gives information about the synthax, not, the rendering. Two solutions have been discussed : 
- use a "title" node or something equivalent
- give the node a css class.
What do we trully want? Whant do we want to be customized?
> Add titled custom block

- README.md
- packages/remark-grid-tables/README.md
Hi !
A quick fix to the README of remark-grid-tables.
> Adding missing definitions to the README of remark-grid-tables

- packages/remark-align/.eslintrc.json
- packages/remark-align/__tests__/__snapshots__/index.js.snap
- packages/remark-align/__tests__/index.js
- packages/remark-align/dist/index.js
- packages/remark-align/package.json
- packages/remark-align/src/index.js
`join('')` would break block content, for instance
```
foo
```
should not become `foo# title`.
2nd commit fixes this and reverts changes in linting config. I also added a test to make sure compiling to Markdown is stable (i.e. compiling n times always yields the same result).
> remark-align: Add Markdown compiler

- packages/remark-custom-blocks/README.md
- packages/remark-custom-blocks/__tests__/index.js
- packages/remark-custom-blocks/dist/index.js
- packages/remark-custom-blocks/src/index.js
See issue #228
https://github.com/zestedesavoir/zmarkdown/issues/228
Their is a test and a README modification.
> Feature to use tags details and summary with rehype

- packages/remark-images-download/__tests__/index.js
- packages/remark-images-download/dist/index.js
- packages/remark-images-download/src/index.js
There are some special malformed URLs like `http://%99:%99@example.com` that `url.parse` can’t decode.
> remark-images-download: handle invalid URLs

- packages/remark-emoticons/__tests__/__snapshots__/index.js.snap
- packages/remark-emoticons/__tests__/index.js
- packages/remark-emoticons/dist/index.js
- packages/remark-emoticons/src/index.js
A trimming issue led to the space in `*foo* :)` to be incorrectly eaten.
> remark-emoticons: fix leading spaces eating bug

- packages/zmarkdown/config/remark.js
Due to portage of remark-iframes from python version.
In python the parameter feature was deleted from URL.
This cause trouble on the client.
> fix(remark-iframes): Fix youtube link client side

- packages/remark-grid-tables/__tests__/index.js
- packages/remark-grid-tables/dist/index.js
- packages/remark-grid-tables/src/index.js
I think I got it. Way easier than I thought. Please review @AmarOk1412 , please also think about edge cases this PR might break?
> remark-grid-tables: preserve spaces on `before` lines

- packages/remark-abbr/__tests__/__snapshots__/index.js.snap
- packages/remark-abbr/__tests__/index.js
- packages/remark-abbr/dist/index.js
- packages/remark-abbr/src/index.js
Previously when we had to remove parent.children[17] and parent.children[21] we would
parent.children.splice(17, 1) and then parent.children.splice(21, 1), this later call removing
index 20 from the original parent.children since it got shifted by any previous .splice call.
#289
> remark-abbr: remove empty p children in correct order

- package-lock.json
- packages/zmarkdown/README.md
- packages/zmarkdown/__tests__/__snapshots__/server.tests.js.snap
- packages/zmarkdown/__tests__/server.tests.js
- packages/zmarkdown/common.js
- packages/zmarkdown/server/handlers.js
On ZDS we have an estimated time of reading for all contents.
For now this indication is not reliable at all because it uses a bare `len(text)` to evaluate the size of content.
This is problematic because it includes mardown-syntax and URL related chars.
In this PR I evaluate the true number of chars by visiting text nodes.
> zmarkdown: Add statistics facility

- packages/remark-custom-blocks/src/index.js
Trying again.
Remove unnecessary escapes. Add necessary escape to correctly 
match brackets. Pattern was incorrectly matching `-` or `[`
followed by the literal string `/{}()*+?.\^$|]` only correctly
replacing the `-` or the `[` with a escape `\`.
> Update regex to correctly match brackets

- packages/remark-grid-tables/__tests__/index.js
- packages/remark-grid-tables/dist/index.js
- packages/remark-grid-tables/src/index.js
Fix: #339
+1 test
The idea of the fix is simple. The problem was that to work with a valide grid, the plugin trim the end of every lines which implies problem when it comes to eat. Now it conserves a version with the spaces to "eat" and still use the valide trimed grid for everything else. 
Do not hesitate to propose another method. :D 
💖
> remark-grid-tables: Ignore spaces at the right

- packages/remark-custom-blocks/README.md
Replaces `fooCustomBlockBlody` with `fooCustomBlockBody`
> Fix typo in remark-custom-blocks README

- packages/rebber-plugins/__tests__/__snapshots__/rebber.test.js.snap
- packages/rebber-plugins/dist/type/customBlocks.js
- packages/rebber-plugins/src/type/customBlocks.js
- packages/zmarkdown/__tests__/__snapshots__/old-suite-latex.test.js.snap
Simply adds `{{` and `}}` on custom block titles for LaTeX rendering in order to prevent problems during the PDF generation. See issue #349 for details of the solution. Tests already handle this, so snapshots were only updated.
~~Please wait for confirmation on the issue before merging.~~
It works, no problems whatsoever.
> rebber-plugins: Protect custom block titles

- README.md
- packages/rehype-footnotes-title/README.md
- packages/remark-align/README.md
- packages/remark-comments/README.md
- packages/remark-custom-blocks/README.md
- packages/remark-grid-tables/README.md
- packages/remark-heading-trailing-spaces/README.md
- packages/remark-numbered-footnotes/README.md
Solves issue #126 ; IDL description was added for
- remark-align;
- remark-comments;
- remark-custom-blocks;
- remark-grid-tables.
It has already been done by some previous PRs for:
- remark-abbr and
- remark-emoticons.
I also added descriptions in the main README for packages where it was missing.
Two questions for me:
- is there a way to use something like "div OR details" instead of "string" for rehype's `hName`?
- maybe we could do something better for my `whatnotCustomBlock`?
Poke @vhf for a review.
> Add IDL description for packages where it was missing

- packages/remark-disable-tokenizers/README.md
As per #358, autoLink currently does nothing for some reason. Until the core issue is found and fixed, others trying to disable autoLinking might find it useful to know they should disable the  `url` tokenizer instead.
> [remark-disable-tokenizers] Add caveat about autoLinking to README

- packages/rebber-plugins/__tests__/__snapshots__/rebber.test.js.snap
- packages/rebber-plugins/__tests__/fixtures/heading.fixture.md
- packages/rebber-plugins/__tests__/fixtures/table.fixture.md
- packages/rebber-plugins/__tests__/rebber.test.js
- packages/rebber-plugins/dist/type/gridTable.js
- packages/rebber-plugins/src/type/gridTable.js
- packages/rebber/__tests__/__snapshots__/mdast.tests.js.snap
- packages/rebber/__tests__/fixtures/remark/table-with-image.text
- packages/rebber/dist/types/image.js
- packages/rebber/dist/types/table.js
- packages/rebber/src/types/image.js
- packages/rebber/src/types/table.js
This PR fixes bug #354 with added **new tests**.
The first thing that was done was to write tests for failing cases and correct erroneous snapshot for one of the previous tests. I may have added a lot of tests compared to the problem, but a wise old man once told me there was never too much tests 🧙‍♂️.
Then, on the problem itself, I added a new option for the image serializer of `rebber`, which allow to inject a matcher for when the image should be renderer inline. The default matcher keeps the old `paragraph` exception and add a new one for `heading`; also, this matcher is enforced in `gridTable` of rebber-plugins and `table`of rebber.
Well, well, well, anyway, the bug is now solved and tests are now good! Be careful before merging; we may need a rebase because PR #355 deals with the …
> Transform images to inline in heading, table and gridTable

- packages/remark-numbered-footnotes/src/index.js
As of https://github.com/syntax-tree/mdast-util-to-hast/pull/31, the footnote label is used for footnotes instead of its identifier. This change brings back numbered footnotes correctly.
This was identified in this issue: https://github.com/gatsbyjs/gatsby/issues/16578
Once this is merged, we're able to fix the affected Gatsby plugin: https://github.com/jlengstorf/gatsby-remark-numbered-footnotes/issues/9
fixes #361
> fix: update labels to use footnote numbers as well as identifiers

- packages/rebber/__tests__/__snapshots__/mdast.tests.js.snap
- packages/rebber/package.json
- packages/rebber/src/types/code.js
- packages/rebber/src/types/inlinecode.js
- packages/rebber/src/types/text.js
- packages/zmarkdown/__tests__/__snapshots__/latex.tests.js.snap
- packages/zmarkdown/__tests__/__snapshots__/old-suite-latex.test.js.snap
* use `collapse-white-space` for inline-code
* use `detab` for code
* use `trim-lines` for text
cf. https://github.com/syntax-tree/mdast-util-to-hast/
fixes the \n bug detected in #342
The generated latex shouldn't impact the way PDF look but please check anyway!
> rebber: fix stringification by replicating mdast-util-to-hast

- packages/remark-grid-tables/__tests__/index.js
- packages/remark-grid-tables/dist/index.js
- packages/remark-grid-tables/src/index.js
Solves issue #369 by removing global length limit on tables; a test was modified: it was used to check that varying-width tables were not allowed, and was replaced by a test checking that two tables that could look alike are well dinstinguinshed by the software.
> Allow varying width table

- packages/rebber-plugins/__tests__/__snapshots__/rebber.test.js.snap
- packages/rebber-plugins/dist/type/align.js
- packages/rebber-plugins/dist/type/gridTable.js
- packages/rebber-plugins/src/type/align.js
- packages/rebber-plugins/src/type/gridTable.js
- packages/zmarkdown/__tests__/__snapshots__/latex.tests.js.snap
- packages/zmarkdown/__tests__/__snapshots__/old-suite-latex.test.js.snap
fix #374 
- uses the "switch command" version of centering and flushright https://cs.overleaf.com/learn/latex/Text_alignment#Right-justified_text
- use parbox instead of nothing in multirow and multicol
- uses `m{dim}` instead of `p{dim}`
- uses  `\endgraph` insteand of `\par` to embody line-break char
> rebber-plugins/zmarkdown: Improve grid table latex rendering

- packages/zmarkdown/__tests__/latex.tests.js
- packages/zmarkdown/__tests__/new-html-suite.test.js
- packages/zmarkdown/common.js
Add the mhchem extension by using KaTeX globals; also adds to tests to make sure:
1. it is well rendered by KaTeX (avoid version conflicts): the test detects the lack of "KaTeX parse error: Undefined control sequence" message;
2. it is directly used without modifications in rebber (which may be overkill, because it is basically math).
> Add mhchem extension to KaTeX (solves #359)

- packages/rebber-plugins/__tests__/__snapshots__/rebber.test.js.snap
- packages/rebber-plugins/dist/type/gridTable.js
- packages/rebber-plugins/dist/type/tableHeader.js
- packages/rebber-plugins/src/type/gridTable.js
- packages/rebber-plugins/src/type/tableHeader.js
- packages/rebber/dist/types/tableRow.js
- packages/rebber/src/types/tableRow.js
- packages/zmarkdown/__tests__/__snapshots__/latex.tests.js.snap
- packages/zmarkdown/__tests__/__snapshots__/old-suite-latex.test.js.snap
This PR aims to fix the font-change line when we switch from header to body.
it embeds two related fixes : 
- do not repeat the line, especially the one with `\bfseries`
- only switch font when we enter the body, not on new line
related to #375
> rebber-plugins/zmarkdown : fix row font handling

- packages/rebber-plugins/__tests__/__snapshots__/rebber.test.js.snap
- packages/rebber-plugins/dist/preprocessors/codeVisitor.js
- packages/rebber-plugins/dist/type/appendix.js
- packages/rebber-plugins/src/preprocessors/codeVisitor.js
- packages/rebber-plugins/src/type/appendix.js
- packages/rebber/__tests__/__snapshots__/mdast.tests.js.snap
- packages/rebber/dist/escaper.js
- packages/rebber/dist/index.js
- packages/rebber/dist/preprocessors/referenceVisitors.js
- packages/rebber/dist/types/linkReference.js
- packages/rebber/src/index.js
- packages/rebber/src/preprocessors/referenceVisitors.js
- packages/rebber/src/types/linkReference.js
- packages/zmarkdown/__tests__/__snapshots__/latex.tests.js.snap
- packages/zmarkdown/__tests__/__snapshots__/old-suite-latex.test.js.snap
- packages/zmarkdown/__tests__/fixtures/latex/code-inside-notes.fixture.md
- packages/zmarkdown/__tests__/latex.tests.js
- packages/zmarkdown/config/rebber.js
Hello,
I tried to fix the "code in footnotes" issue and found some annoying issues in the way we manage appendices.
- references were totally wrong
- no links were provided
- many heading "appendix"
- same appendix number if multi table
This is the state of my work, I still need to know:
- How can I say I am inside an appendix?
- Which command is good to link to reference?
- is there a better way to do what we do?
> rebber/rebber-plugins: fix appendix management for gridtables and footnotes

- package-lock.json
- packages/rebber-plugins/README.md
- packages/rebber-plugins/__tests__/__snapshots__/rebber.test.js.snap
- packages/rebber-plugins/__tests__/fixtures/blocks.fixture.md
- packages/rebber-plugins/__tests__/rebber.test.js
- packages/rebber-plugins/dist/preprocessors/spoilerFlatten.js
- packages/rebber-plugins/dist/type/kbd.js
- packages/rebber-plugins/dist/type/ping.js
- packages/rebber-plugins/src/preprocessors/spoilerFlatten.js
- packages/rebber-plugins/src/type/kbd.js
- packages/rebber-plugins/src/type/ping.js
- packages/rebber/package.json
- packages/zmarkdown/__tests__/__snapshots__/latex.tests.js.snap
- packages/zmarkdown/__tests__/__snapshots__/server.tests.js.snap
- packages/zmarkdown/__tests__/fixtures/latex/blocks.fixture.md
- packages/zmarkdown/__tests__/latex.tests.js
- packages/zmarkdown/__tests__/server.tests.js
- packages/zmarkdown/config/rebber.js
- packages/zmarkdown/server/handlers.js
- packages/zmarkdown/templates/latex-document.js
These are the last changes until next release; I plan on publishing a major version of rebber, which requires the following to be solved:
- add `mhchem` (#359): done and merged;
- array improvements (#374): done and merged;
- array issue (#375): done and merged;
- avoid spoiler in spoiler (#280): done, first in this PR;
- allow to disable custom tokenizers (for #313): done, second in this PR but not sure it solves the issue;
- add options to zmarkdown's LaTeX endpoint (#283 *only*): done, third in this PR;
- send codeblocks to appendices (#299): done and merged;
- add a `\ping` command (none): done, fourth in this PR;
- add missing dependencies to rebber (#384): done, fifth in this PR.
We will be able to publish soon enough, now everything is done.
> [rebber] Lots of corrections and improvements

- packages/remark-grid-tables/__tests__/index.js
- packages/remark-grid-tables/dist/index.js
- packages/remark-grid-tables/src/index.js
I heard that `arduino.md` was taking a long time to parse and render. Profiling zmarkdown with this file showed that 30% of parsing time was spent in `remark-grid-tables`.
By fixing the table detection, time to render `arduino.md` (a ~big file: 15841 lines,  137860 words,   907343 bytes) went from 17s to 7s.
> remark-grid-tables: much faster table start detection

- packages/remark-emoticons/__tests__/__snapshots__/index.js.snap
- packages/remark-emoticons/__tests__/index.js
- packages/remark-emoticons/src/index.js
Solve a bug that made remark think there were no emoticons while it was indeed missing some of them.
> [remark-emoticons] Solve using confusable locators

- packages/remark-emoticons/__tests__/index.js
- packages/remark-emoticons/dist/index.js
- packages/remark-emoticons/src/index.js
When the following conditions were met:
- an emoticon is on a line that also contains text;
- the text contains at least once the first character of the emoticon;
- all of the concerned characters are not preceeded by a space, but the emoticon is.
the emoticon would then not render at all. This was caused by the locator stopping it's search too early; a loop was added to prevent this from happening, and a test was added to match the behavior.
> Solve a bug on emoticons

- packages/rebber/dist/types/code.js
- packages/rebber/src/types/code.js
- packages/zmarkdown/__tests__/__snapshots__/html-suite.test.js.snap
- packages/zmarkdown/__tests__/__snapshots__/latex-suite.test.js.snap
- packages/zmarkdown/__tests__/html-suite.test.js
- packages/zmarkdown/__tests__/latex-suite.test.js
- packages/zmarkdown/utils/code-handler.js
The parser won't crash if the range is entered inverted by the user, i.e. `hl_lines=2-1` instead of `hl_lines=1-2`. In this example, lines 1 and 2 will be highlighted.
Fixes #414.
- This fixes the problem in the HTML export but not in the LaTeX one where the range stays inverted. Don't know if it's a problem.
- I'm still very new to zmarkdown, so I don't know if I should add a test somewhere for that. I guess so?
> Allow inverted ranges in hl_lines

- packages/rebber-plugins/__tests__/__snapshots__/rebber.test.js.snap
- packages/rebber-plugins/__tests__/fixtures/code.fixture.md
- packages/rebber-plugins/__tests__/fixtures/figure-code.fixture.md
- packages/rebber-plugins/__tests__/rebber.test.js
- packages/rebber-plugins/dist/type/figure.js
- packages/rebber-plugins/src/type/figure.js
- packages/rebber/dist/types/code.js
- packages/rebber/src/types/code.js
- packages/zmarkdown/__tests__/__snapshots__/latex-suite.test.js.snap
- packages/zmarkdown/__tests__/latex-suite.test.js
- packages/zmarkdown/config/latex/index.js
- packages/zmarkdown/plugins/remark-code-meta.js
- packages/zmarkdown/renderers/mdast.js
- packages/zmarkdown/utils/code-handler.js
- packages/zmarkdown/utils/latex-code.js
fixes:  #417 
Recent changes to improve HTML code unfortunately had no effect on LaTeX, leading to some bugs such as the one cited above.
In order to fix the problem, I took a kinda complicated path; the idea is that our `code` stringifier for `rebber` was a bit too specific and ZdS-related, so I replaced it by a generic one, and moved the specific ZdS part into `zmarkdown`.
From then, I decided to move the currently HTML-specific part of the stringification into a separate `remark` plugin, so that the changes could be used both by HTML and LaTeX. After all this had been done, I cherry-picked #421 because it would otherwise have failed to merge.
Note: this requires a breaking change for `rebber` AND `rebber-plugin`, but not necessarily for `zmarkdown`, as it still renders as before, with …
> Fix LaTeX hlLine syntax

- packages/remark-disable-tokenizers/__tests__/__snapshots__/index.js.snap
- packages/remark-disable-tokenizers/__tests__/index.js
- packages/remark-disable-tokenizers/dist/index.js
- packages/remark-disable-tokenizers/src/index.js
fixes: #412 
`remark-disabled-tokenizers` replaces a tokenizer by `() => false` instead of `() => true`, and also adds a dummy locator for inline tokenizers.
> [remark-disable-tokenizers] Fix #412

- packages/zmarkdown/__tests__/__snapshots__/server.test.js.snap
- packages/zmarkdown/__tests__/server.test.js
- packages/zmarkdown/server/factories/config-factory.js
- packages/zmarkdown/server/factories/controller-factory.js
- packages/zmarkdown/server/utils/manifest.js
Send request to endpoint `/latex-document`
```json
{
"md": {
"introduction": "myIntro",
"title":        "myTitle",
"children":     [{"introduction": "shiftedIntro"}]
},
"opts": {
"content_type": "article",
"title": "Heloo!",
"authors": ["TALONE"],
"license": "cc-by",
"license_directory": "/home/zaphod",
"smileys_directory": "/home/smileys",
"heading_shift": 2
}
}
```
You get `levelThreeTitle` (as expected because of the heading shift), but also `LevelThreeIntroduction`, which isn't expected. This PR solves the problem and restore the expected behavior.
> [zmarkdown] Fix introduction/conclusion shifts

- packages/zmarkdown/config/html/index.js
Launch a ZMarkdown server, and try to launch multiple requests with Markdown containing footnotes.
All of these request will lead to the same footnote postfix id.
This is a really bad behavior as these ids are supposed to allow to distinguish between footnotes.
It must be present since version 9.0.0 (refactoring).
> [zmarkdown] Fix footnotes random postfix

- packages/zmarkdown/__tests__/regressions.test.js
- packages/zmarkdown/common.js
- packages/zmarkdown/config/html/index.js
Followup PR for #431 : we were not regenerating postfixes for footnotes at all, now we are regenerating them too much, causing the reference to not match the definition.
Because that issue was too stupid to happen again, I added a test to check three things:
- for a footnote, the reference id matches the definition id;
- on a complete content, the second footnote id matches the first;
- **but** when two separate calls are made, the id changes.
Introducing that global variable inside the configuration file should not be a problem with multi-instances, because everything is kept separately (I checked it).
> [zmarkdown] Fix footnotes random postfix (the return)

- .github/workflows/ci.yml
- README.md
- package-lock.json
- packages/remark-ping/__tests__/__snapshots__/index.js.snap
- packages/remark-ping/__tests__/index.js
- packages/remark-ping/dist/index.js
- packages/remark-ping/package.json
- packages/remark-ping/src/index.js
- packages/zmarkdown/config/mdast/index.js
- packages/zmarkdown/package.json
Rewrite almost entirely the parser in `remark-ping` to get better support for Unicode characters in non-fenced pings. For instance, to ping `Moté`, the most natural way would be `@**Moté**`, which didn't work before this PR.
The detection of a ping has been changed as follow:
- before, we used a RegEx, that matched only `\w` characters;
- now, the package contains a complete, RegEx-independant parser, that gets the end of a ping matching characters from Unicode categories *White Space*, *Close Puncutation*, *Final Punctuation*, *Initial Punctuation*, *Open Punctuation* and *Other Punctuation*.
These changes should also make it easier to switch the package to `micromark` soon, as it already consist of a state-machine.
> [remark-ping] Improve parsing to support Unicode

- packages/zmarkdown/server/index.js
Quoting [Sentry's documentation](https://docs.sentry.io/platforms/node/guides/express/):
> The error handler must be before any other error middleware and after all controllers
I tried it on Zeste de Savoir's staging server using this custom route to generate an error:
```js
app.get("/debug-sentry", function mainHandler(req, res) {
throw new Error("My first Sentry error!");
});
```
Currently, the error is logged in `.pm2/logs/` but not sent to Sentry. With these changes, it is logged and sent to Sentry.
> [zmarkdown] Fixes Sentry error handling

- packages/zmarkdown/README.md
Fixes a small typo in zmarkdown package's README.
> Fixes a small typo

- package-lock.json
- packages/rebber-plugins/__tests__/__snapshots__/rebber.test.js.snap
- packages/rebber-plugins/__tests__/rebber.test.js
- packages/rebber-plugins/dist/preprocessors/mathEscape.js
- packages/rebber-plugins/src/preprocessors/mathEscape.js
- packages/remark-ping/__tests__/__snapshots__/index.js.snap
- packages/remark-ping/__tests__/index.js
- packages/remark-ping/dist/index.js
- packages/remark-ping/src/index.js
- packages/zmarkdown/__tests__/__snapshots__/latex-suite.test.js.snap
Fixes two bugs found when testing ZMdv11 on ZdS:
- math sanitation doesn't work on string end and on chained commands (eg. `\vec\frac{1}{2}`);
- empty pings generate a link.
> Two fixes on V11

- .github/workflows/ci.yml
- .github/workflows/prepublish.yml
Node 12 is not LTS anymore, but 18 is the active version. CI Build is not made on 16 instead of 14.
> [meta] Switch tests from Node 12 to Node 18

- package-lock.json
- packages/zmarkdown/__tests__/__snapshots__/server.test.js.snap
- packages/zmarkdown/__tests__/server.test.js
- packages/zmarkdown/server/factories/controller-factory.js
- packages/zmarkdown/server/factories/processor-factory.js
Fixes #448 
The solution involves adding an `enforce_shift` option to the API that can be used to make ZMarkdown follow `heading_shift` in all cases). This option is recommended, and will be the default behavior in the next major version.
What is done for now is to force `heading_shift=2` for HTML contents. This setting is mostly historical, but still needed by `zds-site` today. Changes are required before the next version.
> [zmarkdown] Allow enforcing shifts (fixes #448)

- packages/rebber-plugins/dist/preprocessors/mathEscape.js
- packages/rebber-plugins/src/preprocessors/mathEscape.js
**Bug**: fixes #471 .
**Identification**: double backslashes were treated as two simple backslashes one after the other, causing the sanitizer to delete *all backslashes* in the math block.
**Fix**: two complementary fixes are submitted:
- eat all leading backslashes of the command;
- do not replace in the full math content, but locally.
> [rebber-plugins] Better math sanitation (fixes #471)

- packages/zmarkdown/__tests__/__snapshots__/server.test.js.snap
- packages/zmarkdown/__tests__/server.test.js
- packages/zmarkdown/server/templates/latex-document.js
Add an endpoint option on `latex-document` to specify the publication date of a content.
> [zmarkdown] Allow specifying date on LaTeX files

- packages/remark-grid-tables/src/index.js
When using `remark-grid-tables` as a [docusaurus](https://github.com/facebook/docusaurus) plugin, the following errors occur in the browser console (coming from react-dom-development.js):
```
Warning: Invalid DOM property `colspan`. Did you mean `colSpan`?
... (lines omitted for brevity)
Warning: Invalid DOM property `rowspan`. Did you mean `rowSpan`?
```
This pull request fixes the errors by changing the casings of `colspan` and `rowspan` to  `colSpan` and `rowSpan`.
> [remark-grid-tables] Fix casing for rowspan and colspan

- packages/rebber/__tests__/__snapshots__/mdast.tests.js.snap
- packages/rebber/__tests__/fixtures/code-block-escape.text
- packages/rebber/__tests__/fixtures/image-path-escape.text
- packages/rebber/dist/types/code.js
- packages/rebber/dist/types/image.js
- packages/rebber/src/types/code.js
- packages/rebber/src/types/image.js
- packages/zmarkdown/utils/latex-code.js
1. An RCE was found in images: when an image path contained an `}`, the LaTeX image command could be bypassed to allow malicious code injection.
2. An RCE was found in code blocks: a previous protection measure was unsufficient, thus allowing code blocks to be escaped in LaTeX
> [rebber] Fix two security flaws

- packages/zmarkdown/server/controllers/munin.js
Since status `online` is coded as `0`, `0` was evaluated as `false` and thus the fallback value `3` was taken. Now, we use a ternary operator to test if the status is in the dictionnary to map to a number.
The concerned URL is http://localhost:27272/munin/status.
> [zmarkdown] Fix getting processus status in Munin controller

- README.md
- packages/zmarkdown/package.json
- packages/zmarkdown/webpack.config.js
Fix #494 
1. `npm run build-demo`
2. Open `packages/zmarkdown/public/index.html`
> fix: fix webpack 5 config for live demo

- packages/zmarkdown/__tests__/__snapshots__/html-suite.test.js.snap
- packages/zmarkdown/__tests__/__snapshots__/legacy-suite.test.js.snap
- packages/zmarkdown/__tests__/__snapshots__/server.test.js.snap
- packages/zmarkdown/config/html/index.js
- packages/zmarkdown/postprocessors/html-lazy-load-images.js
- packages/zmarkdown/renderers/html.js
Fixes #496 
Lazy-loading for iframes was added by commit https://github.com/zestedesavoir/zmarkdown/commit/28b2196031cefd1fb8da480bf031fff2814c7187 , this PR aims at lazy-loading all images for ZMarkdown.
Since parsing of images is done by remark directly, implementation was done using a postprocessor, which adds an attribute `loading=lazy` for all images, except emoticons. Since these are guaranteed to be lightweight and served from our servers, I considered they could be eagerly loaded (see condition in postprocessor).
As it is the case with all postprocessors, this one can be easily disabled with a configuration option (`lazyLoadImages`). Since this feature should be ignored by browser not supporting it, I feel like we do not need a major version for enforcing this setting in the …
> [zmarkdown] Lazy-load images

- .github/workflows/ci.yml
- .github/workflows/prepublish.yml
See https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> Update GitHub Actions

- packages/remark-images-download/README.md
- packages/remark-images-download/__mock__/server.js
- packages/remark-images-download/dist/index.js
- packages/remark-images-download/src/index.js
Hello,
This PR solves a problem observed on zestedesavoir.com: downloading images from upload.wikimedia.org failed with a HTTP 403 error, but not on beta.zestedesavoir.com...
After reading [this article](https://meta.wikimedia.org/wiki/User-Agent_policy) and live-patching this package on zestedesavoir.com, I can confirm the lack of user-agent was responsible for these HTTP 403 errors.
It will be hard to test, just believe me that this patch is now used in production. And speaking of test, I don't think we can add a test to cover this case...
I used [this article](https://zestedesavoir.com/billets/4640/mon-installation-domotique/) to debug it (the HomeAssistant logo is an image from Wikimedia).
> [remark-images-download] add a user-agent to requests

- package-lock.json
- packages/zmarkdown/package.json
- packages/zmarkdown/server/factories/controller-factory.js
- packages/zmarkdown/server/index.js
For now, simply restores Sentry error reporting to a working state, but I hope to improve it so that warnings get logged.
Fixes #499
> [meta] Fix Sentry error reporting

- packages/rebber-plugins/__tests__/__snapshots__/rebber.test.js.snap
- packages/rebber-plugins/dist/type/gridTable.js
- packages/rebber-plugins/src/type/gridTable.js
- packages/rebber/README.md
- packages/rebber/__tests__/__snapshots__/mdast.tests.js.snap
- packages/rebber/dist/types/table.js
- packages/rebber/dist/types/tableRow.js
- packages/rebber/src/types/table.js
- packages/rebber/src/types/tableRow.js
- packages/zmarkdown/__tests__/__snapshots__/latex-suite.test.js.snap
- packages/zmarkdown/__tests__/__snapshots__/legacy-suite.test.js.snap
- packages/zmarkdown/config/latex/index.js
Fixes #463 
Fixes #498 
Implement a new table system based on `tabularray` for LaTeX rendering, to solve some bugs and make tables work with TeXLive >2020.
This PR will require changes on the template (I will open a PR in the upcoming days), do not merge until they are done.
I am expecting this PR, even after careful reviewing (which I intend to do), to raise some new bugs in ZMarkdown. It will likely require some bugfix versions before being stable.
> Implement new table system (tabularray) for LaTeX 

- package.json
- packages/remark-abbr/__tests__/__snapshots__/index.js.snap
The only difference in the snapshots seems to be the presence of `\\` backslashes before quote characters.
I'm a little confused by the output, not being all that familiar with jest, but I suspect this is some minor difference in the way that rehype-stringify works and that we don't need to worry about it?
This is just laying a small bit of groundwork, before I attempt to get remark-abbr working with the new version of remark
See also #514
> Add remark-abbr to tests and re-record snapshots
