index.js, package.json, packages/html-blocks/README.md, packages/html-blocks/index.js, packages/html-blocks/inline.js, yarn.lock
=> Handle raw HTML - close #1

index.js, packages/custom-blocks/block.js, packages/custom-blocks/index.js, test/fixtures/zds/extensions/customblock.html, test/fixtures/zds/extensions/customblock.txt, test/test.js
=> Custom blocks

README.md, test/fixtures/zds/extensions/delext.html, test/test.js
=> Fix del extension tests

packages/kbd/inline.js, test/fixtures/zds/extensions/kbd.html, test/fixtures/zds/extensions/kbd.txt
* Gets rid of the regex
* Better tests
* parses what's inside!
=> Refactor kbd; add regression tests

index.js, packages/footnotes-title/README.md, packages/footnotes-title/index.js, packages/numbered-footnotes/README.md, packages/numbered-footnotes/index.js, test/fixtures/extensions/extra/footnote.html, test/fixtures/extensions/extra/footnote_many_footnotes.html, test/test.js
=> Footnote packages

index.js, packages/align/README.md, packages/align/index.js, packages/align/inline.js, public/css/new.css, test/fixtures/zds/extensions/align.html, test/test.js
=> implement zds extension: align

index.js, packages/comments/README.md, packages/comments/index.js, test/fixtures/zds/extensions/comments.html, test/test.js
=> implement zds extension: comments

packages/rehype-abbr/__tests__/fixtures/regression-1.expected.html, packages/rehype-abbr/__tests__/index.js, packages/rehype-abbr/dist/index.js, packages/rehype-abbr/src/index.js
cf #54.
replace function was incorrect.
=> fix rehype-abbr plugin

packages/remark-align/README.md, packages/remark-align/__tests__/fixtures/align-custom-config.expected.html, packages/remark-align/__tests__/fixtures/align-custom-config.fixture.md, packages/remark-align/__tests__/index.js, packages/remark-align/dist/index.js, packages/remark-align/src/index.js, packages/zmarkdown/config.js, packages/zmarkdown/index.js
=> remark-align: configurable class names

packages/typographic-permille/.npmignore, packages/typographic-permille/LICENSE-MIT, packages/typographic-permille/README.md, packages/typographic-permille/__tests__/index.js, packages/typographic-permille/dist/db.js, packages/typographic-permille/dist/index.js, packages/typographic-permille/package.json, packages/typographic-permille/src/db.js, packages/typographic-permille/src/index.js
=> add typographic-permille plugin

package.json, packages/zmarkdown/config.js, packages/zmarkdown/package.json
=> remove typographic-quotes plugin

packages/remark-heading-trailing-spaces/__tests__/fixtures/regression-1.expected.html, packages/remark-heading-trailing-spaces/__tests__/fixtures/regression-1.fixture.md, packages/remark-heading-trailing-spaces/__tests__/index.js, packages/remark-heading-trailing-spaces/dist/index.js, packages/remark-heading-trailing-spaces/package.json, packages/remark-heading-trailing-spaces/src/index.js
=> fix regex to match a full header line

packages/remark-captions/__tests__/__snapshots__/index.js.snap, packages/remark-captions/__tests__/index.js, packages/remark-captions/dist/index.js, packages/remark-captions/src/index.js
internal legends use the last legend
=> remark-captions: fix internal legends

packages/remark-align/__tests__/__snapshots__/index.js.snap, packages/remark-align/__tests__/index.js, packages/remark-align/dist/index.js, packages/remark-align/src/index.js
=> remark-align: make markers escapable

packages/remark-captions/__tests__/__snapshots__/index.js.snap, packages/remark-captions/__tests__/index.js, packages/remark-captions/dist/index.js, packages/remark-captions/src/index.js
=> remark-captions: fix captions for images

packages/rebber/__tests__/__snapshots__/index.js.snap, packages/rebber/__tests__/index.js, packages/rebber/src/types/link.js
=> rebber: escape link URL

packages/remark-ping/README.md
This fixes #131 by adding a "zestedesavoir" agnostic documentation.
=> remark-ping documentation

packages/remark-iframes/README.md
=> fix #130 : remark-iframes doc contains remark-align elements

packages/rebber/__tests__/__snapshots__/index.js.snap, packages/rebber/__tests__/fixtures/code.fixture.md, packages/rebber/__tests__/fixtures/figure.expected.tex, packages/rebber/src/custom-types/figure.js, packages/rebber/src/pre-visitors/codeVisitor.js, packages/rebber/src/pre-visitors/index.js, packages/rebber/src/types/code.js
=> fix quotation and code without language

packages/remark-ping/__tests__/__snapshots__/index.js.snap, packages/remark-ping/__tests__/index.js, packages/remark-ping/dist/index.js, packages/remark-ping/package.json, packages/remark-ping/src/index.js
https://github.com/zestedesavoir/zds-site/issues/4199
=> remark-ping: stringify to markdown; don't ping from blockquotes

packages/zmarkdown/latex-document-template.js
Add license directory to latex template
=> Handle new syntax for licence

packages/zmarkdown/__tests__/__snapshots__/latex.tests.js.snap, packages/zmarkdown/__tests__/__snapshots__/old-suite-latex.test.js.snap, packages/zmarkdown/config/rebber.js
With new version of latex template, inline code use now a custom
environment: CodeInline
=> update/inline-code: Update inline code

packages/zmarkdown/__tests__/__snapshots__/latex.tests.js.snap, packages/zmarkdown/__tests__/__snapshots__/old-suite-latex.test.js.snap, packages/zmarkdown/config/rebber.js
This PR uses the new `\iframe` command in rebber for zmarkdown package.
it ends the development for #176
=> Use the new iframe syntax.

README.md, packages/remark-emoticons/README.md, packages/remark-emoticons/__tests__/__snapshots__/index.js.snap, packages/remark-emoticons/__tests__/index.js, packages/remark-emoticons/dist/index.js, packages/remark-emoticons/src/index.js
=> Add compiler to remark-emoticons

packages/remark-ping/README.md, packages/remark-ping/__tests__/__snapshots__/index.js.snap, packages/remark-ping/__tests__/index.js, packages/remark-ping/dist/index.js, packages/remark-ping/src/index.js, packages/zmarkdown/__tests__/server.tests.js
`[@Sandhose](http://example.com) ->`
```html
<a href="http://example.com">
<span class="ping ping-in-link">
@<span class="ping-username">Sandhose</span>
</span>
</a>
```
`@Sandhose ->`
```html
<a href="/membres/voir/Sandhose/" rel="nofollow" class="ping ping-link">
@<span class="ping-username">Sandhose</span>
</a>
```
=> remark-ping: no ping link in links

packages/remark-grid-tables/__tests__/index.js, packages/remark-grid-tables/dist/index.js, packages/remark-grid-tables/package.json, packages/remark-grid-tables/src/index.js
Explicit enough amha.
I just want to talk about 1 thing. I think that with the test : 
```markdown
+----- A -----+
|             |
+-------------+
|             |
+-------------+
```
Is a regression since now it's parsed as a table. See the [snapshot](https://github.com/zestedesavoir/zmarkdown/blob/d446425880f9337c8eddadc0e3fdb0b7c296dca6/packages/remark-grid-tables/__tests__/__snapshots__/index.js.snap#L47).
With love 💌
=> Stringify to markdown

packages/remark-abbr/__tests__/index.js, packages/remark-abbr/dist/index.js, packages/remark-abbr/src/index.js
=> remark-abbr: abbr ending with period are now parsed

package-lock.json, packages/rebber-plugins/__tests__/__snapshots__/rebber.test.js.snap, packages/rebber-plugins/__tests__/fixtures/code.fixture.md, packages/rebber/dist/types/code.js, packages/rebber/src/types/code.js, packages/remark-images-download/package.json, packages/zmarkdown/__tests__/__snapshots__/old-suite-latex.test.js.snap
=> rebber-plugins: fix highlighted lines string

packages/remark-captions/README.md
=> Change "caption" to "captions"

packages/zmarkdown/__tests__/__snapshots__/latex.tests.js.snap, packages/zmarkdown/__tests__/__snapshots__/old-suite-latex.test.js.snap, packages/zmarkdown/config/rebber.js
=> zmarkdown: fix rebber iframe macro

packages/rebber-plugins/__tests__/__snapshots__/rebber.test.js.snap, packages/rebber-plugins/dist/type/figure.js, packages/rebber-plugins/src/type/figure.js, packages/rebber/__tests__/__snapshots__/mdast.tests.js.snap, packages/rebber/__tests__/fixtures/remark/invalid-link-definition.text, packages/rebber/__tests__/fixtures/remark/title-attributes.text, packages/rebber/dist/index.js, packages/rebber/dist/types/linkReference.js, packages/rebber/dist/types/table.js, packages/rebber/package.json, packages/rebber/src/index.js, packages/rebber/src/types/linkReference.js, packages/rebber/src/types/table.js, packages/zmarkdown/__tests__/__snapshots__/latex.tests.js.snap, packages/zmarkdown/__tests__/__snapshots__/old-suite-latex.test.js.snap
This PR should fix #275 #276 #277 #278.
=> Captions; references

packages/rebber-plugins/__tests__/__snapshots__/rebber.test.js.snap, packages/rebber-plugins/dist/type/gridTable.js, packages/rebber-plugins/src/type/gridTable.js, packages/rebber/README.md, packages/rebber/__tests__/__snapshots__/mdast.tests.js.snap, packages/rebber/dist/types/table.js, packages/rebber/dist/types/tableRow.js, packages/rebber/src/types/table.js, packages/rebber/src/types/tableRow.js, packages/zmarkdown/__tests__/__snapshots__/latex.tests.js.snap, packages/zmarkdown/__tests__/__snapshots__/old-suite-latex.test.js.snap
=> rebber/zmarkdown : enhance table rendering in latex

packages/zmarkdown/README.md, packages/zmarkdown/client/index.js, packages/zmarkdown/common.js, packages/zmarkdown/modules/zhtml.js, packages/zmarkdown/modules/zlatex.js, packages/zmarkdown/public/main.css, packages/zmarkdown/public/script.js, packages/zmarkdown/webpack.config.js
https://github.com/zestedesavoir/zmarkdown/issues/259
@Heziode Please review (do it commit after commit if that helps).
=> zmarkdown client fixes

packages/zmarkdown/public/index.html
Again… this is due to Split.js lib (and unpkg redirect).
=> fix(live-demo): Fix external dependencies

packages/zmarkdown/config/remark.js
Cf. https://github.com/zestedesavoir/zds-site/issues/5042
=> Add smiley :popcorn:

packages/zmarkdown/config/remark.js
Cf. https://github.com/zestedesavoir/zds-site/pull/4951#issuecomment-410361589
=> Add smiley " :B "

packages/zmarkdown/.babelrc
This is related to [this](https://github.com/webpack/webpack/issues/4039#issuecomment-492793025) post.
Fix #329
=> Remove ignore core-js in babel config

packages/remark-custom-blocks/__tests__/index.js, packages/remark-custom-blocks/dist/index.js
=> remark-custom-blocks: build and add tests

packages/zmarkdown/README.md, packages/zmarkdown/common.js
I try to improve README.md for npm page and outsider
https://github.com/A-312/zmarkdown/blob/patch-4/packages/zmarkdown/README.md
=>  Improve README.md for npm page and outsider

packages/rebber-plugins/__tests__/__snapshots__/rebber.test.js.snap, packages/rebber/__tests__/__snapshots__/mdast.tests.js.snap, packages/rebber/dist/escaper.js, packages/rebber/dist/types/listItem.js, packages/rebber/src/types/listItem.js, packages/zmarkdown/__tests__/__snapshots__/latex-suite.test.js.snap, packages/zmarkdown/__tests__/__snapshots__/legacy-suite.test.js.snap
=> rebber: solve issue #398

packages/zmarkdown/server/utils/manifest.js
Small fix on titles depth not handled correctly.
Opening a PR because I want to see if tests pass. They fail on my side for no obvious reason...
=> [zmarkdown] Fix titles depth on manifest rendering

packages/rebber-plugins/dist/preprocessors/prepareQuizz.js, packages/rebber-plugins/src/preprocessors/prepareQuizz.js, packages/zmarkdown/__tests__/__snapshots__/latex-suite.test.js.snap, packages/zmarkdown/__tests__/__snapshots__/server.test.js.snap
Send the answer list in the non-hidden block.
=> rebber-plugins: fix quizz latexification

packages/rebber-plugins/__tests__/__snapshots__/rebber.test.js.snap, packages/rebber-plugins/dist/preprocessors/headingVisitor.js, packages/rebber-plugins/dist/type/footnoteDefinition.js, packages/rebber-plugins/dist/type/footnoteReference.js, packages/rebber-plugins/src/preprocessors/headingVisitor.js, packages/rebber-plugins/src/type/footnoteDefinition.js, packages/rebber-plugins/src/type/footnoteReference.js, packages/zmarkdown/__tests__/__snapshots__/latex-suite.test.js.snap
=> [rebber-plugins] Allow footnote reference in title

package-lock.json, packages/remark-fix-guillemets/__tests__/__snapshots__/index.js.snap, packages/typographic-guillemets/__tests__/index.js, packages/typographic-guillemets/dist/index.js, packages/typographic-guillemets/src/index.js, packages/zmarkdown/package.json, packages/zmarkdown/renderers/mdast.js, packages/zmarkdown/server/controllers/munin.js
Some commits for the new version of ZMarkdown.
- Fixes #475 
- #477 was fixed in another PR, #478 
- Update Sentry
- Fixes #469
=> Preparing ZMarkdown 11.2

packages/remark-grid-tables/dist/index.js, packages/remark-grid-tables/src/index.js
Cell contents is not preprocessed to selectively trim
whitespace in such a way that leading whitespace inside of a markdown
code-block is not trimmed beyond the indentation "set" by the opening
of said code-block. Previously all leading whitespace was trimmed,
making code-block indentetaion within a table-cell impossible.
=> Properly support code-blocks in remark-grid-tables
